enum ConversationState {
  INITIALIZING = 'INITIALIZING',
  IDLE = 'IDLE',
  USER_SPEAKING = 'USER_SPEAKING',
  ASSISTANT_SPEAKING = 'ASSISTANT_SPEAKING',
  PAUSED = 'PAUSED',
  FATAL_ERROR = 'FATAL_ERROR'
}

export default ConversationState;